repos:
 -  repo: https://github.com/psf/black-pre-commit
    rev: 25.1.0
    hooks:
    -   id: black
        language_version: python3.13

 -  repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff

