name: Python CI/CD Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  python-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit bandit black ruff pre-commit coverage

      - name: Run pip-audit (Dependency Vulnerability Scan)
        run: |
          pip-audit || echo "No vulnerabilities found."

      - name: Run Ruff Linter
        run: |
          ruff . --output-format=github

      - name: Run Black (Check Only)
        run: |
          black --check .

      - name: Run Pre-commit Hooks
        run: |
          pre-commit run --all-files


      - name: Run Bandit Security Scan
        run: |
          bandit -r . -ll

      - name: Run Unit Tests with Coverage
        run: |
          coverage run -m unittest discover -s . -p "test_*.py"
          coverage report
          coverage xml

      - name: Enforce Coverage Threshold
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml

      - name: Verify Coverage Threshold
        run: |
          coverage report --fail-under=90
